stockfish.make_moves_from_current_position(["e2e4"])
# stockfish.make_moves_from_current_position(["e7e5"])
# stockfish.make_moves_from_current_position(["b1c3"])
# stockfish.make_moves_from_current_position(["d8g5"])
# stockfish.make_moves_from_current_position(["d2d4"])
# stockfish.make_moves_from_current_position(["d7d5"])